version: "3.9"
services:
  iad:
    image: "iad"
    ports:
      - "127.0.0.1:9109:9109"
    environment:
      # Your ENV config here
    depends_on:
      - db
    tty: true
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
